### ISSUE TITLE
Empty strings inconsistently converted to NULL's when using df.to_gbq()

### ISSUE THREAD

**Issue by jerome-asselin-ivadolabs** [googleapis/python-bigquery-pandas#366]
Here is a reproducible example of inconsistent conversion of empty strings to NULL when exporting to Bigquery.
```
import pandas as pd
from google.cloud import bigquery

df1 = pd.DataFrame.from_dict([{'a': ""}])
df2 = pd.DataFrame.from_dict([{'a': "", 'b': ""}])

df1.to_gbq('aa_temp.df1') # Keeps empty string, as expected.
df2.to_gbq('aa_temp.df2') # Converts empty strings to null values.

client = bigquery.Client()
print(client.list_rows('aa_temp.df1').to_dataframe())
print(client.list_rows('aa_temp.df2').to_dataframe())
```
Actual Output:
```
  a
0  
      a     b
0  None  None
```
Expected Output:
```
  a
0  
      a     b
0    
```
Using python 3.7, pandas 1.2.4, pandas-gbq 0.15.0.

**Comment by tseaver** [comment]
Running through this in the debugger, I found that BigQuery correctly infers schema for both dataframes (all fields are `STRING` w/ `NULLABLE`). The difference between the two dataframes seems to be in how `dataframe.to_csv` is generating the file used to upload the data:

```python
>>> import pandas as pd
>>> df1 = pd.DataFrame.from_dict([{'a': ""}])
>>> df1.to_csv(None, index=False, header=False)
'""\n'
>>> df2 = pd.DataFrame.from_dict([{'a': "", 'b': ""}])
>>> df2.to_csv(None, index=False, header=False)
',\n'
```

When loading the file dumped from `df1` preserves the empty string, because that file has the `""`.  When loading the file dumped from `df2`, which does not have the `""`, the columns are loaded (properly) as null values.

**Comment by tswast** [comment]
The other option we can do is to start sending Parquet data instead of CSV, as that should correctly disambiguate between null and empty string in all cases.
