### ISSUE TITLE
pyarrow.lib.ArrowTypeError: Expected bytes, got a 'dict' object

### ISSUE THREAD

**Issue by ivanpugachtd** [googleapis/python-bigquery-pandas#452]
Hi!
there is a problem when trying to load using pandas-gbq which using pyarrow a column of the list (array) or dictionary (json) type into the table, while the GBQ documentation says that structure types such as array or json are supported,

```
df = pd.DataFrame(
                {
                    "my_string": ["a", "b", "c"],
                    "my_int64": [1, 2, 3],
                    "my_float64": [4.0, 5.0, 6.0],
                    "my_bool1": [True, False, True],
                    "my_bool2": [False, True, False],
                    "my_struct": [{"test":"str1"},{"test":"str2"},{"test":"str3"}],
                }
            )
pandas_gbq.to_gbq(df, **gbq_params)
```

as a result, a stacktrace error occurs:

- in bq_to_arrow_array
- return pyarrow.Array.from_pandas(series, type=arrow_type)
- File "pyarrow/array.pxi", line 913, in pyarrow.lib.Array.from_pandas
- File "pyarrow/array.pxi", line 311, in pyarrow.lib.array
- File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
- File "pyarrow/error.pxi", line 122, in pyarrow.lib.check_status
- pyarrow.lib.ArrowTypeError: Expected bytes, got a 'dict' object

Can anyone help with it please?

**Comment by tswast** [comment]
Is this writing to an existing table? Could you share the schema of the destination table?

**Comment by ivanpugachtd** [comment]
Hi, @tswast 
I am trying to upload data to the new table, more precisely I tried both
versions:
pyarrow==6.0.1
pandas-gbq==0.16.0

In fact I was able to upload data, only if I using json.dumps() on the column which has list or dict type in there

**Comment by grzesir** [comment]
any updates on this? getting the same error

**Comment by tswast** [comment]
> I am trying to upload data to the new table, more precisely I tried both

Ah, that probably explains it. Currently, `pandas-gbq` attempts to determine a schema locally based on the dtypes it detects. It likely gets this wrong for the struct/array data.

I believe we can avoid this problem with https://github.com/googleapis/python-bigquery-pandas/issues/339 where instead of pandas-gbq creating the table, we create the table as part of the load job.

**Comment by nabor-slalom-greenparksports** [comment]
Has there been any progress on updating this issue. I am seeing the same error message. 

Could we elaborate on:

I believe we can avoid this problem with https://github.com/googleapis/python-bigquery-pandas/issues/339 where instead of pandas-gbq creating the table, we create the table as part of the load job.

As I am seeing the same issue even with a created table, and using (**if_exists='replace'**):

```
pandas_gbq.to_gbq(dataframe, table_id, project_id=project_id, if_exists='replace')
```

**Comment by tswast** [comment]
The reason the fix in https://github.com/googleapis/python-bigquery-pandas/issues/339 didn't work is that pandas-gbq isn't using the load job to actually create the table, so it doesn't benefit from the same logic that google-cloud-bigquery has.

In https://github.com/googleapis/python-bigquery-pandas/pull/814 I'm taking the opposite approach and moving some logic from google-cloud-bigquery to pandas-gbq as part of an effort to make pandas-gbq the canonical location for all bigquery + pandas logic and reduce redundancy across our suite of libraries.

Thanks everyone for your contributions and clear test cases. These have influenced the test cases I made in #814.
