### ISSUE TITLE
Conda performance is a feature.

### ISSUE THREAD

**Issue by adonoho** [googleapis/python-bigquery-pandas#659]
**Is your feature request related to a problem? Please describe.**

I just moved to using `pandas-gbq` instead of communicating with a Postgres database. My `conda` installation times have radically increased. Please remember that performance is a feature. By the way, just adding `pandas-gbq` to my `environment.yml` file, which already included `pandas`, resulted in some unavailable library error. Nuking the whole environment and reinstalling with just `pandas-gbq` resulted in an extremely long install time. I suspect you have some dependency problem. 

 **Describe the solution you'd like**

I want `pandas-gbq` to install in a similar amount of time as `pandas` itself. 

 **Describe alternatives you've considered**

I could move to mamba forge. Might solve the problem. A better solution is hoping it is a bug that your fine team can fix.

 **Additional context**

Here's the environment.yml file:
```
name: MatrixCompletion
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - scipy
  - cvxpy
  - scikit-learn
  - pandas-gbq
  - sqlalchemy
  - pg8000
  - cloud-sql-python-connector
  - dask
prefix: /Users/awd/opt/anaconda3/envs/MatrixCompletion
```

**Comment by chalmerlowe** [comment]
Thanks for submitting this comment.
I took a look and yes... `conda` installs are slow. 
`mamba` installs are significantly faster (by an order of magnitude OR more)

I am not a `conda` guru so I can't say for sure what is causing `conda` to be so much slower than `mamba`.

In looking at my workload and our manpower, I don't foresee myself being able to tackle this issue right away, especially since using `mamba` seems like a really viable workaround, so I am gonna close this.

**Comment by adonoho** [comment]
Resource limits are a reality. Understood.

I, nonetheless, believe you have some configuration problem with `pandas-compat`. Please see this error after running a `conda env update`.
```
ImportError: cannot import name 'lzip' from 'pandas.compat' (/Users/awd/opt/anaconda3/envs/MatrixCompletion/lib/python3.10/site-packages/pandas/compat/__init__.py)
``` 
Anon,
Andrew
